### PR TITLE
refactor OpenAPI schemas for modularity

### PR DESCRIPTION
**Pull request by tomkralidis**
As part of the [May 2022 Space Partitions Code Sprint](https://github.com/opengeospatial/developer-events/wiki/Space-Partitions-Code-Sprint), this PR refactors the EDR OpenAPI schemas for modularity/reusability.

Manually adding @jerstlouis here, who has implemented this approach for OGC API - Coverages / OGC API - Tiles.

### CODE REVIEW

**Comment by chris-little** [comment]
This PR will give better structure of schemas, with no normative changes to function. It is also compatible with the approach taken by API-Coverages and API-Tiles. @jerstlouis

**Review by chris-little — APPROVED** [review]
Looked like garbled predictive text! Approved

**Comment by tomkralidis** [comment]
Note: PR is updated based on recent changes in #364

**Review by chris-little — APPROVED** [review]
Bundles are good!

**Review by chris-little — APPROVED** [review]

**Review by chris-little — APPROVED** [review]

**Review by m-burgoyne — APPROVED** [review]

**Comment by chris-little** [comment]
agreded at EDR API SWG 78

**Pull request merged**
