### PR TITLE
Web API guidelines 1

### PR DESCRIPTION
**Pull request by chris-little**
Fill ed out Web API Guidelines for V1.1, V1.2, and Part 2 V1.0

### CODE REVIEW

**Comment by chris-little** [comment]
Please check for omission, mistakes, better English etc

**Comment by chris-little** [comment]
@tomkralidis Can you check the statements for Part 2 please?

**Review by tomkralidis — APPROVED** [review]
Looks good to me!  +1 for Part 2 as well, thanks @chris-little :)

**Comment by chris-little** [comment]
@m-burgoyne Are you happy with the [statements](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/ogc-web-api-guidelines) for V1.2 (and V1.1, which are almost identical to V1.0)?

**Comment by m-burgoyne** [comment]
@chris-little , yes the core principles haven't changed

**Review by m-burgoyne — APPROVED** [review]

**Pull request merged**
