### PR TITLE
address Public Review comments

### PR DESCRIPTION
**Pull request by tomkralidis**
Addresses #535 and #537

### CODE REVIEW

**Review by chris-little — APPROVED** [review]
Thanks @tomkralidis . I'll let "comprised of" pass!

**Review by m-burgoyne — APPROVED** [review]

**Review by chris-little — APPROVED** [review]
OK

**Comment by chris-little** [comment]
@tomkralidis When do you want this merged?

**Comment by tomkralidis** [comment]
@chris-little I'm almost done updates per our discussion in #535, which would be in this PR.  I'll notify when ready (by MetOceanDWG session next week).

**Comment by tomkralidis** [comment]
Now updated in 2efeb58bae6f32c90ff5b52af0ff4260acf73798

**Review by chris-little — APPROVED** [review]
I've corrected the spelling of Clemens' name

**Comment by cportele** [comment]
Thanks @tomkralidis. 

Maybe it is my English, but I do not understand what definition of the new link relation type is trying to say. The current text is:

> Refers to a resource that is accessible via an event driven is comprised of members of the collection represented by the link's context.

I would have expected something like:

> Refers to a resource that publishes notifications about changes to the current context.

**Comment by tomkralidis** [comment]
Mea culpa @cportele, this was a copy/paste fumble.

I really wanted to write:

>  Refers to a resource that is accessible via an event driven workflow.

...given I wanted to emphasis a Publish-Subscribe flavour in the definition.  But I think your suggestion is more concise. Thanks.

PR in #550

**Pull request merged**
