### PR TITLE
Other updates for v1.2

### PR DESCRIPTION
**Pull request by m-burgoyne**
Add changes for limit query parameter and other informative text

### CODE REVIEW

**Review by chris-little — APPROVED** [review]
Looks good

**Review by ghobona — CHANGES_REQUESTED** [review]
Line 22 in the file position.yaml has `strin` instead of `string`. See attached.

Screenshot 2024-01-09 at 17 01 20

**Comment by m-burgoyne** [comment]
@ghobona Thanks

**Review by chris-little — APPROVED** [review]

**Review by solson-nws — APPROVED** [review]
Looks good with typo fixes

**Comment by m-burgoyne** [comment]
Replaced by #577

**Pull request closed without merging**
