### PR TITLE
Fix for  Issue #324

### PR DESCRIPTION
**Pull request by m-burgoyne**
Updated CRS84 references in the Abstract tests to use the canonical URI
Removed invalid Instance metadata tag causing one of the issues raised in #326

### CODE REVIEW

**Review by chris-little — APPROVED** [review]
@m-burgoyne @ghobona These all look good to me. We still have to ensure the query endpoints for the `instance` path are included.

**Comment by m-burgoyne** [comment]
@chris-little The query endpoints for the `instance` path are included, the problem was an invalid tag split the locations query into it's own group

**Review by chris-little — COMMENTED** [review]
@m-burgoyne @ghobona @dblodgett-usgs Approved, as I now understand the error - queries for instances are catered for, because one chooses a `collectionId` to select an instance of a collection.

**Review by dblodgett-usgs — APPROVED** [review]

**Comment by chris-little** [comment]
EDR API SWG 67 agreed to PR

**Pull request merged**
