### PR TITLE
Update annex c

### PR DESCRIPTION
**Pull request by m-burgoyne**
Section C1 and C3 were both API description examples, I have merged the two sections under the title API Description examples.  (Fix for #153)

This change also fixes relative links to the descriptive images in the resolutionx and resolutionz documentation.

### CODE REVIEW

**Comment by m-burgoyne** [comment]
- Replaced github URL's with internal references #156
- Removed Environmental Resources link #160 
- Replaced single row tables with plain text #161

**Review by chris-little — APPROVED** [review]
Should we refer to OpenQPI 3.0.2 or 3.0.3?
Otherwise, fine.

**Comment by m-burgoyne** [comment]
- OpenAPI version changed to 3.0.3 (3.0.2 -> 3.0.3 is a patch release and not a change to the standard)
- Examples added for the Radius query #163

**Comment by chris-little** [comment]
Editorial changes and examples not altering specification

**Pull request merged**
