### PR TITLE
Fix inconsistencies in Unit documentation

### PR DESCRIPTION
**Pull request by m-burgoyne**
Fixes for problem identified in #486

### CODE REVIEW

**Review by chris-little — APPROVED** [review]
Looks good. Hoepfully Igor agrees

**Comment by chris-little** [comment]
@iandruska-ibl Could you then approve formally please?

**Comment by chris-little** [comment]
Approved and merged at EDR API SWG 113.

**Review by solson-nws — APPROVED** [review]
Looks good

**Comment by chris-little** [comment]
Approved and merged at EDR API SWG 113.

**Pull request merged**
