### PR TITLE
Improve pagination

### PR DESCRIPTION
**Pull request by m-burgoyne**
Page breaks added to improve the layout of documentation when it is converted to PDF

### CODE REVIEW

**Comment by m-burgoyne** [comment]
@chris-little it was meant for the Master branch

**Comment by ghobona** [comment]
Regarding the [Improve Pagination](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/293/commits/1e0d1182711741109d4112d48d6abbf2be79e9d0) commit, please do not use the vocprez URLs e.g. http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/rel/iana/1.0/self . 

Only use the canonical URIs e.g. http://www.opengis.net/def/rel/iana/1.0/self.

**Comment by m-burgoyne** [comment]
@ghobona updated to correct the invalid URL's

**Review by chris-little — APPROVED** [review]
Looks good to me.

**Review by chris-little — APPROVED** [review]

**Comment by ghobona** [comment]
@m-burgoyne Reviewing this commit https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/293/commits/252fccf9a937d74b2af6f5eaf93bd3d2f9be1cbe

I noticed that you edited ATS_class_instances.adoc but the adoc file is not imported into the EDR document.

There is therefore no ‘instances’ Conformance Class in the ATS.

Could you please include the ATS_class_instances.adoc file if it is intended to used in the EDR document?

**Comment by ghobona** [comment]
@m-burgoyne Please note that URIs of Conformance Classes use `/conf/`, however those of Requirements Classes use `/req/` instead.

For example, see attached.

Screenshot 2021-05-12 at 13 00 10

**Comment by m-burgoyne** [comment]
@ghobona After modifiying ATS_class_instances.adoc I realised that it duplicated tests in ATS_class_queries.adoc so the file will be removed, the Requirement Classes have now been updated to fix the invalid URI's.

**Comment by ghobona** [comment]
@m-burgoyne I will shortly move the metanorma version into the public repo (master branch) so that we can work on the same document. Please do not edit the Standard in the public repo until then.

**Review by chris-little — APPROVED** [review]
Looks OK apart from some funny syntax (which @m-burgoyne says are AsciiDoc bookmarks)

**Review by dblodgett-usgs — APPROVED** [review]
This all scans fine. Based on Gobe's responses here, I think this is very well reviewed.

**Pull request merged**
