### PR TITLE
update ATS / REQ traceability

### PR DESCRIPTION
**Pull request by bradh**
Relates #202.

Please check before merging - I found clauses that look the same, but I don't know enough about EDR to be sure that the traceability is necessary / sufficient.

There are still issues I couldn't resolve:

Found the following requirements that do not have matching test references:
/req/oas30/conformance
/req/oas30/oas-common
/req/core/datetime-parameter
Found tests that refer to a requirement, but these requirements were not found:
/conf/core/rc-bbox-definition
/conf/core/rc-bbox-response
/conf/core/rc-time-definition
/conf/core/rc-time-response
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition

### CODE REVIEW

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne These first requirements should come from OGC API-Common Core and therefore that is where the test should be too?
/req/oas30/conformance
/req/oas30/oas-common
/req/core/datetime-parameter

These requirements also come from OGC API-Common Core
/conf/core/rc-bbox-definition
/conf/core/rc-bbox-response
/conf/core/rc-time-definition
/conf/core/rc-time-response

@tomkralidis @m-burgoyne were these several tests not updated when the requirements were?
/req/edr/z-definition
?

**Comment by bradh** [comment]
If the requirement is a partial URI, it isn't pointing to Common. Note https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/clause_5_conventions.adoc#identifiers 

> The normative provisions in this standard are denoted by the URI:
> 
> http://www.opengis.net/spec/ogcapi-edr-1/1.0
> 
> All Requirements and Conformance Tests that appear in this document are denoted by partial URIs which are relative to this base.

That is, `/req/oas30/conformance` means ` http://www.opengis.net/spec/ogcapi-edr-1/1.0/req/oas30/conformance`. 

More generally, if we have a requirement that is "complies with (some document)", then there should be a matching ATS clause to check that compliance (which could point to that document for the test process if it has one, or could specify it). It doesn't matter if its some part of Common or something else. As a practical matter, the ETS implementers only need to code what is in the ATS, so if we want compliance checked, it needs to be in the ATS.

**Comment by bradh** [comment]
How about we move the discussion on what this doesn't do back over to #202?

**Review by chris-little — APPROVED** [review]
@bradh Sterling work! Thank you.

**Review by m-burgoyne — APPROVED** [review]

**Pull request merged**
