### PR TITLE
Improve domainType validation

### PR DESCRIPTION
**Pull request by m-burgoyne**
Updated to add support for CoverageCollections and fix errors in schema definitions issue #341

### CODE REVIEW

**Review by tomkralidis — APPROVED** [review]
Good work @m-burgoyne.  I am guessing we would pull out the CoverageJSON defs from the EDR schemas once CoverageJSON has a formal home?

**Comment by m-burgoyne** [comment]
I agree @tomkralidis, once the official schemas are published the definitions in our repository should be removed.

**Review by chris-little — APPROVED** [review]

**Comment by m-burgoyne** [comment]
Updated to use the schema definitions developed for the CoverageJSON validator

**Review by tomkralidis — APPROVED** [review]

**Review by chris-little — APPROVED** [review]
Looks OK .

**Comment by chris-little** [comment]
Agreed at EDR API SWG69

**Pull request merged**
