### PR TITLE
Fixes for errors identified in issue #431

### PR DESCRIPTION
**Pull request by m-burgoyne**

### CODE REVIEW

**Review by chris-little — APPROVED** [review]

**Review by chris-little — APPROVED** [review]
Great proof reading by @ghobona !

**Review by tomkralidis — APPROVED** [review]
Thanks for the updates! Aside/no impact comment: it might be valuable to normalize URL examples (i..e `https://example.org/collections/global_model/area`).

**Comment by m-burgoyne** [comment]
@tomkralidis Good idea, I have updated the URL's

**Review by chris-little — APPROVED** [review]
@tomkralidis Thanks for the suggestion.
@m-burgoyne Thanks for the slog doing it.

**Pull request merged**
