### PR TITLE
remove JSON schemas

### PR DESCRIPTION
**Pull request by tomkralidis**
cc @solson-nws @ShaneMill1 @m-burgoyne @chris-little 

Consistent with other OGC API specifications, the YAML schemas should be our single point of truth from which to reuse and transform to JSON schemas if required.

### CODE REVIEW

**Review by ShaneMill1 — APPROVED** [review]
looks good to me

**Review by chris-little — APPROVED** [review]
Found a jyamlson schema. Changed inline.

**Comment by tomkralidis** [comment]
What?  You haven't heard of the jyamlson format!?  Kidding -- thanks @chris-little!

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne  If and when we move to OpenAPI V3.1, I think it would only JSON Schema, rather than YAML.
Perhaps we should maintain both sets of fragments until confirmed switch. Let's discuss at the next SWG.

**Comment by chris-little** [comment]
@tomkralidis is there a JSON schema definition of `datetime` and where is it?
As in the spec `A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at datetime.yaml.`

**Comment by tomkralidis** [comment]
I would recommend one and only one representation, as it is relatively to go back/forth between them with tools.  +1 to discuss further.

**Comment by tomkralidis** [comment]
> @tomkralidis is there a JSON schema definition of datetime and where is it?
As in the spec A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at datetime.yaml.

We have them locally in EDR here:
- https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/parameters/datetime.yaml
- https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/parameters/datetime.json

The EDR specification itself is pointing to https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/parameters/datetime.yaml which is 404.  The correct spot for this now is https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/parameters/datetime.yaml

Since the local EDR and OGC API - Common `datetime` parameter definitions are identical, suggest we use OGC API - Common's definition.  Will open a PR with an update.

**Comment by tomkralidis** [comment]
>> Since the local EDR and OGC API - Common datetime parameter definitions are identical, suggest we use OGC API - Common's definition. Will open a PR with an update.

Added to this PR.

**Pull request merged**
