### PR TITLE
reorganize repository in preparation for extensions

### PR DESCRIPTION
**Pull request by tomkralidis**
As part of preparing Part 2: Pub/Sub as an extension, this PR does some housekeeping only, namely:

- move `standard` to `core/standard`
- remove files which are built (doc, pdf, etc.) from version control
- move information md files to `docs/` (I've keep the Web API Guidelines at the root of the repo [required], as well as the overview, which is used by ogcapi.ogc.org)

There will be an `extensions/` directory created following this PR as a result.

Here's a view of how the repository looks if/once this PR is merged: https://github.com/tomkralidis/ogcapi-environmental-data-retrieval/tree/housekeeping

### CODE REVIEW

**Review by dblodgett-usgs — APPROVED** [review]

**Review by m-burgoyne — APPROVED** [review]

**Review by chris-little — APPROVED** [review]
Looks safe!

**Comment by chris-little** [comment]
@ghobona Just checking that you are happy with this. We are restructuring the repo into Core (Part 1) and PubSub (Part 2).

**Comment by ghobona** [comment]
@chris-little I have no objection to the restructuring of the repo.

**Comment by ghobona** [comment]
@m-burgoyne @chris-little Have the changes in the 2023-07-26 commits of the [1.1.0 branch](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commits/1.1.0) been applied to the [housekeeping](https://github.com/tomkralidis/ogcapi-environmental-data-retrieval/commits/housekeeping) branch (i.e. the source of this PR)? 

If they have not, then the SWG should make the changes after merging the PR to ensure that there is no regression when v1.2 is eventually approved. The SWG, can of course, make the changes before merging the PR as well.

**Comment by m-burgoyne** [comment]
@ghobona, I believe that the [housekeeping](https://github.com/tomkralidis/ogcapi-environmental-data-retrieval/commits/housekeeping) branch is based on the current main branch which includes PR #450 to fix the same schema erros as the  2023-07-26 commits (PR #449) of the [1.1.0 ](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commits/1.1.0)branch

**Comment by chris-little** [comment]
Merged at EDR API SWG 105.

**Pull request merged**
