### PR TITLE
rename files, fix instances

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR makes the following changes, for consideration:

- renames `collection.yaml` into `collectionInfo.yaml` to be consistent with naming patterns in other OGC API specifications
- updates `instances.yaml` to refer to an `instances` property, which is a list of `collectionInfo.yaml` objects (isn't an instance just a site-specific collection?), thus removing `instanceInfo.yaml`.  This enables an instance to have fulsome metadata (parameters, etc.) per #242 

UPDATE: removes `collectionInfo.yaml` and `instanceInfo.yaml` and fixes references.

cc @chris-little @m-burgoyne @ShaneMill1 @iandruska-ibl

### CODE REVIEW

**Comment by cportele** [comment]
@tomkralidis - regarding the first item: Features had originally used `collectionInfo.yaml`, but changed it to `collection.yaml` in June 2019 as part of a terminology cleanup. Common was forked before and did not sync that change. 

`collection.yaml` is also what is used in the OGC schema repository: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml. 

On the other hand, the name of the file is not important as it has no impact on any instances.

**Comment by tomkralidis** [comment]
Thanks @cportele, renamed file for good measure while we are here.

**Review by m-burgoyne — APPROVED** [review]

**Review by chris-little — APPROVED** [review]

**Comment by chris-little** [comment]
Merge after discussion in SWG for visibility and other API SWGs confirmation

**Comment by chris-little** [comment]
EDR API SWG 46 agreed

**Pull request merged**
